server:
  port: 18080

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: user-service-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  datasource:
    url: jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console